# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: ${self:custom.appconfig.stackName}
plugins:
  - serverless-offline
package:
  individually: false
  excludeDevDependencies: true
  patterns:
    - 'node_modules/**'
    - '!node_modules/aws-sdk/**'
    - config/
    - dist/
custom:
  file: ${file(./config/serverlessconfig.json)}
  appconfig: ${file(./config/appconfig.json)}
  custom:
  serverless-offline:
    resourceRoutes: true
    useChildProcesses: true
  webpack:
    includeModules: true
    packager: 'npm'
  region: ${self:custom.file.awsRegion, 'eu-central-1'}
provider:
  stage: ${self:custom.file.stage, 'dev'}
  name: aws
  runtime: nodejs12.x
  region: ${self:custom.region}
  stackName: ${self:custom.appconfig.stackName}
  stackTags: # Tags that will be added to each of the deployment resources
    jsonsls: ${self:custom.appconfig.stackName}
  environment:
    NODE_ENV: ${self:provider.stage}
    s3Bucket: ${self:custom.file.s3Bucket}
    s3File: ${self:custom.file.s3File}
    basePath: ${self:custom.file.basePath}
    COGNITO_USER_POOL_ID:
      Ref: CognitoUserPool
    region: ${self:provider.region}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  apiGateway: # Optional API Gateway global config
    shouldStartNameWithService: true
    binaryMediaTypes: # Optional binary media types the API might return
      - '*/*'
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 's3:*'
          Resource:
            - '*'
        - Effect: 'Allow'
          Action:
            - 's3:*'
          Resource:
            - 'arn:aws:s3:::${self:custom.file.s3Bucket}/*'
        - Effect: 'Allow'
          Action:
            - 'ssm:GetParameter'
          Resource: '*'

# The `functions` block defines what code to deploy
functions:
  app:
    timeout: 15
    handler: ./dist/handler.handler
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: /
          method: ANY
          private: ${self:custom.appconfig.enableApiKeyAuth}
          cors:
            origin: '*' # <-- Specify allowed origin
            headers: # <-- Specify allowed headers
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
      - http:
          path: '{proxy+}'
          method: ANY
          private: ${self:custom.appconfig.enableApiKeyAuth}
          cors:
            origin: '*' # <-- Specify allowed origin
            headers: # <-- Specify allowed headers
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
resources:
  Resources:
    # S3 Bucket
    s3BucketStorage:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.file.s3Bucket}
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        # Generate a name based on the stage
        UserPoolName: ${self:service}.${self:provider.stage}-user
        # Set email as an alias
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email
    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        # Generate an app client name based on the stage
        ClientName: ${self:service}.${self:provider.stage}-client
        UserPoolId:
          Ref: CognitoUserPool
        ExplicitAuthFlows:
          - ALLOW_USER_PASSWORD_AUTH
        GenerateSecret: false

  # Print out the Id of the User Pool that is created
  Outputs:
    UserPoolId:
      Value:
        Ref: CognitoUserPool
    UserPoolClientId:
      Value:
        Ref: CognitoUserPoolClient
